name: adguard-home-services
services:
  adguard-home-services:
    image: adguard/adguardhome:v0.107.77
    container_name: adguard-home-services
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 33563631616
        reservations:
          memory: "67108864"
          devices: []
    labels:
      icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
    restart: unless-stopped
    networks:
      Services:
        ipv4_address: 192.168.3.252
    volumes:
      - type: bind
        source: /DATA/AppData/adguard-home-dmz/data/work
        target: /opt/adguardhome/work
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/adguard-home-dmz/data/conf
        target: /opt/adguardhome/conf
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /opt/adguardhome/work
          description:
            en_us: "Container Path: /opt/adguardhome/work"
        - container: /opt/adguardhome/conf
          description:
            en_us: "Container Path: /opt/adguardhome/conf"

    privileged: false

networks:
  Services:
    name: Services
    external: true

x-casaos:
  architectures:
    - amd64
    - arm64
  main: adguard-home-services
  category: cheetahx7x
  developer: cheetahx7x
  author: cheetahx7x
  tagline:
    en_us: Network-wide ads & trackers blocking DNS server.
  description:
    en_us: AdGuard Home is a network-wide software for blocking ads and tracking.
      After you set it up, it'll cover all your home devices, and you won't need
      any client-side software for that. Learn more on our official Github
      repository.
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
  scheme: https
  hostname: adguard.fabi.ng
  port_map: "443"
  index: /
  title:
    en_us: AdGuard Home Services
  version: "1.0"
  updateAt: "2026-06-09"
  releaseNotes:
  website: "https://adguard.com/en/adguard-home/overview.html"
  repo: "https://github.com/AdguardTeam/Adguardhome"
  support: "https://github.com/AdguardTeam/Adguardhome/issues"
  docs: "https://github.com/AdguardTeam/Adguardhome"